---

- name: Gather facts for a VM
  community.vmware.vmware_vm_info:
    hostname: "{{ vmware.host }}"
    username: "{{ vmware.username }}"
    password: "{{ vmware.password }}"
    vm_type: vm
    vm_name: '{{ ansible_hostname }}'
    validate_certs: false
  delegate_to: localhost
  register: vm_info

- name: Remove all snapshots of a VM
  community.vmware.vmware_guest_snapshot:
    hostname: "{{ vmware.host }}"
    username: "{{ vmware.username }}"
    password: "{{ vmware.password }}"
    moid: "{{ vm_info.virtual_machines[0].moid }}"
    datacenter: "{{ vm_info.virtual_machines[0].datacenter }}"
    validate_certs: false
    state: remove_all
  delegate_to: localhost
